TRUNCATE TABLE STUDENT;

INSERT INTO STUDENT (STUDENT_ID, NAME, GRADUATION_YEAR) VALUES (1, 'Jim', 2007);
INSERT INTO STUDENT (STUDENT_ID, NAME, GRADUATION_YEAR) VALUES (2, 'Alex', 2012);
INSERT INTO STUDENT (STUDENT_ID, NAME, GRADUATION_YEAR) VALUES (3, 'Tim', 2002);
INSERT INTO STUDENT (STUDENT_ID, NAME, GRADUATION_YEAR) VALUES (4, 'Justin', 2009);
